@apiUrl = http://localhost:3000/api
//{{apiUrl}}
@authToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmEzOWFiOTE3MDk0ZTM0YTNlYzUwNDkiLCJub21lIjoiQ3Jpc3RpYW4iLCJpYXQiOjE2NTU1ODgxMDksImV4cCI6MTY1NTU5MTcwOX0.QMhGAeII2NkBSv-g47Akg1A1ythPGFKwE4r0rftUZEc

# Obter a lista de andamentos
GET {{apiUrl}}/andamentos
Content-Type: application/json
x-auth-token: {{authToken}}
###

# Inserir novo andamento
POST {{apiUrl}}/andamentos
Content-Type: application/json
x-auth-token: {{authToken}}

{
 "dataHora": "2022-03-27",
 "titulo": "Andamento teste", 
 "descricao": "Finalizar testes de andamento",
 "atividade": "623f9cb7d34bd647e4c45930",
 "colaborador": "623a733205a4286ab31c786c"
}
###

# Alterar um andamento
PUT {{apiUrl}}/andamentos
Content-Type: application/json
x-auth-token: {{authToken}}

{
 "_id": "62ad39200a8abe53b083fe12",   
 "dataHora": "2022-03-27",
 "titulo": "Andamento teste para excluir", 
 "descricao": "Finalizar testes de andamento",
 "atividade": "6290d9456a354ae514549ca7",
 "colaborador": "62a3951417094e34a3ec4ff7"
}
###

# Excluir um andamento
DELETE {{apiUrl}}/andamentos/6290d9f76a354ae514549cbf
Content-Type: application/json
x-auth-token: {{authToken}}
###

# Obter pelo id de andamento
GET {{apiUrl}}/andamentos/623fa2bc050c92172ca9953d
Content-Type: application/json
###

# Obter andamentos filtrando
GET {{apiUrl}}/andamentos/filtro/ovo
Content-Type: application/json
###