@apiUrl = http://localhost:3000/api
@authToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmEzOWFiOTE3MDk0ZTM0YTNlYzUwNDkiLCJub21lIjoiQ3Jpc3RpYW4iLCJpYXQiOjE2NTU1OTIwMDEsImV4cCI6MTY1NTU5NTYwMX0.QfrCZb3z-QUsKaqXtiIIgdbqk2ECKgIWemuUF5IAmsA
//{{apiUrl}}

# Obter a lista de atividades
GET {{apiUrl}}/atividades
Content-Type: application/json
x-auth-token: {{authToken}}
###

# Inserir nova atividade
POST {{apiUrl}}/atividades
Content-Type: application/json
x-auth-token: {{authToken}}

{
 "titulo": "Reparo Epson", 
 "descricao": "Conserto realizado na impressora!",
 "status": "Em Andamento",
 "prazo": "2002-06-28",
 "agendaInicio": "2022-06-18",
 "dataHoraTermino": "2022-06-28",
 "requisicao": "62ae49ad80ef3537bcfa8e11",
 "colaborador": "62a3a54017094e34a3ec5084"
}
###

# Alterar uma atividade
PUT {{apiUrl}}/atividades
Content-Type: application/json
x-auth-token: {{authToken}}

{
 "_id": "6290d9456a354ae514549ca7",   
 "titulo": "Atividade concluída! 100%", 
 "descricao": "Codificar métodos para API de Atividades!",
 "status": "Concluído",
 "prazo": "2002-05-12",
 "agendaInicio": "2022-03-26",
 "dataHoraTermino": "2022-03-27",
 "requisicao": "62a39a3517094e34a3ec503e",
 "colaborador": "62a3a54017094e34a3ec5084"
}
###

# Excluir uma atividade
DELETE {{apiUrl}}/atividades/623f9a86d34bd647e4c458ec
Content-Type: application/json
x-auth-token: {{authToken}}
###

# Obter pelo id de atividade
GET {{apiUrl}}/atividades/623f9b20d34bd647e4c458f3
Content-Type: application/json
x-auth-token: {{authToken}}
###

# Obter atividade filtrando
GET {{apiUrl}}/atividades/filtro/teste
Content-Type: application/json
x-auth-token: {{authToken}}
###