@apiUrl = http://localhost:3000/api
@authToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmEzOWFiOTE3MDk0ZTM0YTNlYzUwNDkiLCJub21lIjoiQ3Jpc3RpYW4iLCJpYXQiOjE2NTU1MzA0NzcsImV4cCI6MTY1NTUzNDA3N30.wxoINEg-6mkNwuuD_bAsbGgrTmx0svJ_Jz0H6aNynUw

#Autenticação de colaborador
POST {{apiUrl}}/login
Content-Type: application/json
x-auth-token: {{authToken}}

{
    "email" : "cristianpetry@upf.br",
    "senha" : "1234"
}
###

# Obter a lista de colaboradores
GET {{apiUrl}}/colaboradores
Content-Type: application/json
###

# Inserir colaborador
POST {{apiUrl}}/colaboradores
Content-Type: application/json

{
 "nome": "Cristian",
 "email": "cristianpetry@upf.br",
 "senha": "1234"
}
###


# Alterar colaborador
PUT {{apiUrl}}/colaboradores
Content-Type: application/json

{
 "_id": "62917619ec4e3262085fb8be",
 "nome": "Jaqson alterado",
 "email": "jaqson@teste.com",
 "senha": "12344"
}
###


# Excluir um colaborador
DELETE {{apiUrl}}/colaboradores/62a39ab917094e34a3ec5049
Content-Type: application/json
###


# Obter pelo id de colaborador
GET {{apiUrl}}/colaboradores/62a39ab917094e34a3ec5049
Content-Type: application/json
###


# Obter colaboradores filtrando
GET {{apiUrl}}/colaboradores/filtro/cristian
Content-Type: application/json
###
