@apiUrl = http://localhost:3000/api

@authToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmEzOWFiOTE3MDk0ZTM0YTNlYzUwNDkiLCJub21lIjoiQ3Jpc3RpYW4iLCJpYXQiOjE2NTU1OTIwMDEsImV4cCI6MTY1NTU5NTYwMX0.QfrCZb3z-QUsKaqXtiIIgdbqk2ECKgIWemuUF5IAmsA
//{{apiUrl}}

# Obter a lista de requisições
GET {{apiUrl}}/requisicoes
Content-Type: application/json
x-auth-token: {{authToken}}
###

# Inserir nova requisição
POST {{apiUrl}}/requisicoes
Content-Type: application/json
x-auth-token: {{authToken}}

{
 "titulo": "Reparo", 
 "descricao": "Reparo impressora",
 "status": "Aberto",
 "prazoAtendimento": "2002-05-12",
 "tipoRequisicao": "62ad44de0a8abe53b083fe51",
 "solicitante": "62a39eeb17094e34a3ec507e"
}
###

# Alterar requisição
PUT {{apiUrl}}/requisicoes
Content-Type: application/json
x-auth-token: {{authToken}}

{
 "_id": "62a3991317094e34a3ec5024",
 "titulo": "Requisição de Processamento Mudada", 
 "descricao": "Para processar meu teste!",
 "status": "Em andamento",
 "prazoAtendimento": "2002-05-12",
 "tipoRequisicao": "62a3980717094e34a3ec5017",
 "solicitante": "62a399cb17094e34a3ec502b"
}
###

# Excluir uma requisição
DELETE {{apiUrl}}/requisicoes/62a3991317094e34a3ec5024
Content-Type: application/json
x-auth-token: {{authToken}}
###

# Obter pelo id de requisição
GET {{apiUrl}}/requisicoes/62a39a3517094e34a3ec503e
Content-Type: application/json
x-auth-token: {{authToken}}
###

# Obter requisição filtrando
GET {{apiUrl}}/requisicoes/filtro/andamento
Content-Type: application/json
x-auth-token: {{authToken}}
###