@apiUrl = http://localhost:3000/api
//{{apiUrl}}
@authToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmEzOWFiOTE3MDk0ZTM0YTNlYzUwNDkiLCJub21lIjoiQ3Jpc3RpYW4iLCJpYXQiOjE2NTU1ODgxMDksImV4cCI6MTY1NTU5MTcwOX0.QMhGAeII2NkBSv-g47Akg1A1ythPGFKwE4r0rftUZEc

# Obter a lista de solicitantes
GET {{apiUrl}}/solicitantes
Content-Type: application/json
x-auth-token: {{authToken}}
###

# Inserir novo solicitante
POST {{apiUrl}}/solicitantes
Content-Type: application/json
x-auth-token: {{authToken}}

{
 "nome": "Enio Beppler", 
 "email": "jbeppler64@yahoo.com.br",
 "senha": "12345"
}
###

# Alterar solicitante
PUT {{apiUrl}}/solicitantes
Content-Type: application/json
x-auth-token: {{authToken}}

{
 "_id": "62a399cb17094e34a3ec502b",
 "nome": "Pato Donald", 
 "email": "donald@upf.br",
 "senha": "1234"
}
###

# Excluir um solicitante
DELETE {{apiUrl}}/solicitantes/62a39e8817094e34a3ec5076
Content-Type: application/json
x-auth-token: {{authToken}}
###

# Obter pelo id de solicitante
GET {{apiUrl}}/solicitantes/6290d8706a354ae514549c81
Content-Type: application/json
x-auth-token: {{authToken}}
###

# Obter solicitante filtrando
GET {{apiUrl}}/solicitantes/filtro/chi
Content-Type: application/json
x-auth-token: {{authToken}}
###