@apiUrl = http://localhost:3000/api
//{{apiUrl}}

# Obter a lista de tipos de requisicao
GET {{apiUrl}}/tipoRequisicoes
Content-Type: application/json
###

# Inserir novo tipo de requisicao
POST {{apiUrl}}/tipoRequisicoes
Content-Type: application/json

{
 "descricao": "Testes automatizados"
}

###

# Alterar um tiporequisicao
PUT {{apiUrl}}/tipoRequisicoes
Content-Type: application/json

{
  "_id": "6290d69b6a354ae514549c52",
 "descricao": "Lançar nova release"
}
###

# Excluir um tiporequisicao pelo id
DELETE {{apiUrl}}/tipoRequisicoes/6290d69b6a354ae514549c52
Content-Type: application/json
###

# Obter tiporequisicao pelo id
GET {{apiUrl}}/tipoRequisicoes/6290d69b6a354ae514549c52
Content-Type: application/json
###

# Obter tiporequisicao filtrando
GET {{apiUrl}}/tipoRequisicoes/filtro/release
Content-Type: application/json
###