


#Obter lista de livros 
GET http://localhost:3001/api/livros
Content-Type: application/json
###

#Inserir novo livro
POST http://localhost:3001/api/livros
Content-Type: application/json

{
    "titulo": "IT",
    "genero": "Terror",
    "autor": "Stephen King",
    "quantidade": 2,
    "precoUn": 69.99
}
###

# Alterar livro
PUT http://localhost:3001/api/livros
Content-Type: application/json

{
    "_id": "62673e6ac84db1514f841102",
    "titulo": "IT",
    "genero": "Terror",
    "autor": "Stephen King",
    "quantidade": 3,
    "precoUn": 39.9
}
###



# Excluir um livro
DELETE http://localhost:3001/api/livros/62674037c84db1514f841114
Content-Type: application/json
###

# Livro sem o autor
POST http://localhost:3001/api/livros
Content-Type: application/json

{
 "titulo": "O livro do cemitério",
 "genero": "Fantasia",
 "autor": "",
 "quantidade": 12,
 "precoUn": 25.95
}
###

# Obter pelo id do livro
GET http://localhost:3001/api/livros/5f6cb80e07cee54810920f5f
Content-Type: application/json
###
# Obter livros filtrando
GET http://localhost:3001/api/livros/filtro/coraline
Content-Type: application/json
###